create table if not exists tbl_user
(
    id   bigint primary key auto_increment,
    name varchar(64),
    age  int
);

insert into tbl_user(name, age)
values ('zhangsan1', 36),
       ('zhangsan2', 36),
       ('zhangsan3', 36),
       ('zhangsan4', 36),
       ('zhangsan5', 36),
       ('zhangsan6', 36),
       ('zhangsan7', 36),
       ('zhangsan8', 36),
       ('zhangsan9', 36),
       ('zhangsan10', 36),
       ('zhangsan11', 36),
       ('zhangsan12', 36),
       ('zhangsan13', 36),
       ('zhangsan14', 36),
       ('zhangsan15', 36),
       ('zhangsan16', 36),
       ('zhangsan17', 36),
       ('zhangsan18', 36),
       ('zhangsan', 36),
       ('zhangsan', 36),
       ('zhangsan', 36),
       ('zhangsan', 36),
       ('zhangsan', 36),
       ('zhangsan', 36),
       ('zhangsan', 36),
       ('zhangsan', 36),
       ('zhangsan', 36),
       ('zhangsan', 36),
       ('zhangsan', 36),
       ('zhangsan', 36),
       ('zhangsan', 36),
       ('zhangsan', 36),
       ('zhangsan', 36),
       ('zhangsan', 36),
       ('zhangsan', 36),
       ('zhangsan', 36),
       ('zhangsan', 36),
       ('zhangsan', 36),
       ('zhangsan', 36),
       ('zhangsan', 36),
       ('zhangsan', 36),
       ('zhangsan', 36),
       ('zhangsan', 36),
       ('zhangsan', 36),
       ('zhangsan', 36),
       ('zhangsan', 36),
       ('zhangsan', 36),
       ('zhangsan', 36),
       ('zhangsan', 36),
       ('zhangsan1001', 36);